### ISSUE TITLE
I hope to find supplementary materials related to the paper.

### ISSUE THREAD

**Issue by DDKdakuan** [THU-LYJ-Lab/dmt#2]
Hello,

Thank you very much for making part of the DMT code available. The DMT method you've proposed has been quite inspiring for our research. We noticed that your paper (https://ieeexplore.ieee.org/document/10614866) frequently references supplementary materials, but unfortunately, we were unable to locate them within the paper. We look forward to your response.

Best regards.

**Comment by thuxmf** [comment]
Hi, the IEEE url you mentioned has already been attached to the supplementary materials. They are addressed at the bottom at the page (https://ieeexplore.ieee.org/document/10614866/media#media), instead of within the paper.

**Comment by DDKdakuan** [comment]
Thank you for your sincere response.
