### ISSUE TITLE
!!!SOME questions about the parameter set --diffusion_path

### ISSUE THREAD

**Issue by tianjilong123** [THU-LYJ-Lab/dmt#3]
你好，我在复现代码的过程中，test时遇到了一个参数的疑问。
在使用自己的数据集时，我已经有AB两个不同域的图像。除了运行train_dmt.py文件外，我得到了权重文件。
但是在test_dmt.py中，我需要设置一个参数--diffusion_path,给出的示例表示这是一个预训练DPM权重。
那么我应该如何去设置这个参数的路径呢，是还需要在DDPM上训练一个权重文件吗，如果是，我应该使用什么代码呢。

期待回复，万分感谢，十分迫切。

**Comment by thuxmf** [comment]
Thanks for following and reproducing our work!

1. The whole DMT method is proposed to employ a pre-trained DPM on image translation, so it is quite straightforward, and introduced in both **Sec. 4.1 (Implementation details) of original paper** and [README.md](https://github.com/THU-LYJ-Lab/dmt/blob/956f6177cc03776bfc7036a346e9b5d1a865219b/README.md?plain=1#L41), that we use the pre-trained DPM checkpoints.
2. What one needs to do is to load pre-trained DPM checkpoints through `--diffusion_path`, simply as what you have mentioned.
3. I can hardly understand your confusion on the codebase of underlying DPMs. Also as claimed in [README.md](https://github.com/THU-LYJ-Lab/dmt/blob/956f6177cc03776bfc7036a346e9b5d1a865219b/README.md?plain=1#L42), the whole DMT codebase is model-agnostic, *i.e.*, it is compatible with **any** kind of GAN backbone (as the translator) and DPM (as the denoiser).
