### ISSUE TITLE
wrong 

### ISSUE THREAD

**Issue by 06Liz** [THU-LYJ-Lab/dmt#5]
ModuleNotFoundError: No module named 'models.networks.sync_batchnorm'

**Comment by thuxmf** [comment]
It is not the problem of our repo. Please **at first** carefully check all details of [TSIT](https://github.com/EndlessSora/TSIT), as we stated at the very beginning in the [Installation](https://github.com/THU-LYJ-Lab/dmt/blob/956f6177cc03776bfc7036a346e9b5d1a865219b/README.md?plain=1#L12C39-L12C82).
